import { Listing } from '../types';

export const MOCK_LISTINGS: Listing[] = [
  {
    id: '1',
    title: 'Modern Sunset Apartment',
    location: 'Westlands, Nairobi',
    price: 85000,
    type: 'Apartment',
    beds: 2,
    baths: 2,
    sqft: 1200,
    description: 'A beautiful modern apartment with a stunning view of the sunset. Located in the heart of Westlands, close to all amenities. Features a spacious living area, modern kitchen, and balcony.',
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80&w=1000',
    ],
    emoji: '🌇',
    isVerified: true,
    isSaved: false,
    amenities: ['WiFi', 'Parking', 'Gym', 'Pool', 'Security'],
    landlord: {
      id: 'l1',
      name: 'John Doe',
      avatar: 'https://i.pravatar.cc/150?u=l1',
      rating: 4.8,
    },
    postedAt: '2 days ago',
    status: 'Available',
  },
  {
    id: '2',
    title: 'Cozy Studio in Kilimani',
    location: 'Kilimani, Nairobi',
    price: 45000,
    type: 'Studio',
    beds: 1,
    baths: 1,
    sqft: 500,
    description: 'Perfect for young professionals. This cozy studio is well-maintained and located in a quiet neighborhood. Includes high-speed internet and backup generator.',
    images: [
      'https://images.unsplash.com/photo-1536376074432-ad7374f11bd4?auto=format&fit=crop&q=80&w=1000'
    ],
    emoji: '🏢',
    isVerified: false,
    isSaved: true,
    amenities: ['WiFi', 'Backup Power', 'Security'],
    landlord: {
      id: 'l2',
      name: 'Jane Smith',
      avatar: 'https://i.pravatar.cc/150?u=l2',
      rating: 4.5,
    },
    postedAt: '5 hours ago',
    status: 'Available',
  },
  {
    id: '3',
    title: 'Luxury Villa with Garden',
    location: 'Karen, Nairobi',
    price: 250000,
    type: 'Villa',
    beds: 4,
    baths: 4,
    sqft: 3500,
    description: 'Experience luxury living in this magnificent villa. Features a large private garden, swimming pool, and servant quarters. Located in a secure gated community in Karen.',
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&q=80&w=1000',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=1000'
    ],
    emoji: '🏡',
    isVerified: true,
    isSaved: false,
    amenities: ['Pool', 'Garden', 'Security', 'Parking', 'Gym'],
    landlord: {
      id: 'l3',
      name: 'Robert King',
      avatar: 'https://i.pravatar.cc/150?u=l3',
      rating: 4.9,
    },
    postedAt: '1 week ago',
    status: 'Available',
  },
  {
    id: '4',
    title: 'Spacious Family House',
    location: 'Lavington, Nairobi',
    price: 150000,
    type: 'House',
    beds: 3,
    baths: 3,
    sqft: 2200,
    description: 'A spacious family home in the serene neighborhood of Lavington. Open plan kitchen, large bedrooms, and a cozy backyard for family gatherings.',
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=1000'
    ],
    emoji: '🏠',
    isVerified: true,
    isSaved: false,
    amenities: ['Garden', 'Parking', 'WiFi', 'Security'],
    landlord: {
      id: 'l4',
      name: 'Mary Wanjiku',
      avatar: 'https://i.pravatar.cc/150?u=l4',
      rating: 4.7,
    },
    postedAt: '3 days ago',
    status: 'Available',
  },
];
